id: P002902
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:27:22.814880
source_metadata:
  id: bdr:W1KG12516
  title: ཀརྨ་བཀའ་བརྒྱུད་ཀྱི་ཆོས་སྤྱོད།
  author: ''
  volumes:
    5af4e2001b6746ffb1c44d8bbf6d7256:
      image_group_id: I1KG12550
      title: ''
      volume_number: 1
      total_pages: 646
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
